recursos_humanos:
    path:     /
    defaults: { _controller: RecursosHumanosBundle:Home:index }

folha_pagamento:
    path:     /
    defaults: { _controller: RecursosHumanosBundle:Home:index }

pessoal_aposentadoria_index:
   resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_aposentadoria.yml"
   prefix:   /pessoal/aposentadoria

pessoal_relatorios:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_relatorios.yml"
    prefix:   /pessoal/relatorios

pessoal_conselho_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_conselho.yml"
    prefix:   /pessoal/conselho/

pessoal_requisito_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_requisito.yml"
    prefix:   /pessoal/requisito/

pessoal_cbo_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_cbo.yml"
    prefix:   /pessoal/cbo/

pessoal_cargo_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_cargo.yml"
    prefix:   /pessoal/cargo/

pessoal_ferias_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_ferias.yml"
    prefix:   /pessoal/ferias/

pessoal_regime_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_regime.yml"
    prefix:   /pessoal/regime/

pessoal_cid_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_cid.yml"
    prefix:   /pessoal/cid

pessoal_assentamento_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_assentamento.yml"
    prefix:   /pessoal/assentamento

pessoal_condicao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_condicaoassentamento.yml"
    prefix:   /pessoal/condicao-assentamento

pessoal_sefip_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_sefip.yml"
    prefix:   /pessoal/sefip

pessoal_rescisao_home:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_rescisao.yml"
    prefix:   /pessoal/rescisao

pessoal_gerenciar_vagas:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_gerenciar_vagas.yml"
    prefix:   /pessoal/gerenciar-vagas

pessoal_subdivisao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_subdivisao.yml"
    prefix:   /pessoal/subdivisao/consultar/{id}

pessoal_subdivisao:
    resource: "@RecursosHumanosBundle/Resources/config/routing/pessoal_caso_causa_subdivisao.yml"
    prefix:   /pessoal/subdivisao/

ponto_formato_importacao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_formato_importacao.yml"
    prefix:   /ponto/formato-importacao/

ponto_configuracao_parametros_gerais:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_configuracao_parametros_gerais.yml"
    prefix:   /ponto/configuracao-parametros-gerais/

ponto_configuracao_horas_extras_2:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_configuracao_horas_extras_2.yml"
    prefix:   /ponto/configuracao-horas-extras-2/

ponto_configuracao_banco_horas:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_configuracao_horas_extras_2.yml"
    prefix:   /ponto/configuracao-banco-horas/

ponto_configuracao_relogio_ponto:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_configuracao_relogio_ponto.yml"
    prefix:   /ponto/configuracao-relogio-ponto/

ponto_justificativa_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ponto_justificativa.yml"
    prefix:   /ponto/justificativa/

calendario_feriado_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/calendario_feriado.yml"
    prefix:   /calendario/feriado/

calendario_calendario_cadastro_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/calendario_calendario_cadastro.yml"
    prefix:   /calendario/

calendario_calendario_ponto_facultativo_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/calendario_calendario_ponto_facultativo.yml"
    prefix:   /calendario/calendario-ponto-facultativo/

calendario_calendario_dia_compensado_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/calendario_calendario_dia_compensado.yml"
    prefix:   /calendario/calendario-dia-compensado/

folha_pagamento_folha_rescisao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folha_rescisao.yml"
    prefix:   /folha-pagamento/folha-rescisao

folha_pagamento_periodo_rotina_mensal_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_rotina_mensal.yml"
    prefix:   /folha-pagamento/rotina-mensal

folha_pagamento_relatorios:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_relatorios.yml"
    prefix:   /folha-pagamento/relatorios

folha_pagamento_folha_complementar_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folha_complementar.yml"
    prefix:   /folha-pagamento/folha-complementar

folha_pagamento_irrf_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_irrf.yml"
    prefix:   /folha-pagamento/irrf

folha_pagamento_configuracao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_configuracao.yml"
    prefix:   /folha-pagamento/configuracao

diarias_diaria_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/diarias_diaria.yml"
    prefix:   /diarias/diaria

folhapagamento_sindicato_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_sindicato.yml"
    prefix:   /folha-pagamento/sindicato

folhapagamento_folha_salario_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folha_salario.yml"
    prefix:   /folha-pagamento/folha-salario

folhapagamento_folha_ferias_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folha_ferias.yml"
    prefix:   /folha-pagamento/folha-ferias

folhapagamento_folha_13_salario_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folha_13_salario.yml"
    prefix: /folha-pagamento/folha-13-salario

folhapagamento_fgts_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folhapagamento_fgts.yml"
    prefix: /folha-pagamento/fgts

folhapagamento_previdencia_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_previdencia.yml"
    prefix: /folha-pagamento/previdencia

informacoes_pagamentos_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_exportar_pagamentos.yml"
    prefix:   /informacoes/exportar-pagamentos

informacoes_sefip_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_sefip.yml"
    prefix:   /informacoes/sefip

informacoes_rais_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_rais.yml"
    prefix:   /informacoes/rais

informacoes_caged_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_caged.yml"
    prefix:   /informacoes/caged

informacoes_pasep_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_pasep.yml"
    prefix:   /informacoes/pasep

informacoes_dirf_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_dirf.yml"
    prefix:   /informacoes/dirf

informacoes_consignacao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_consignacao.yml"
    prefix:   /informacoes/consignacao

informacoes_ipers_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_ipers.yml"
    prefix:   /informacoes/ipers

informacoes_configuracao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao.yml"
    prefix:   /informacoes/configuracao

informacoes_configuracao_rais_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_rais.yml"
    prefix:   /informacoes/configuracao/rais

informacoes_configuracao_hsbc_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_hsbc.yml"
    prefix:   /informacoes/configuracao/hsbc

informacoes_configuracao_dirf_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_dirf.yml"
    prefix:   /informacoes/configuracao/dirf

informacoes_configuracao_caixa_economica:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_caixa_economica_federal.yml"
    prefix:   /informacoes/configuracao/caixa-economica

informacoes_configuracao_pasep:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_pasep.yml"
    prefix:   /informacoes/configuracao/pasep

informacoes_configuracao_caged:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_caged.yml"
    prefix:   /informacoes/configuracao/caged

informacoes_configuracao_bradesco:
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_configuracao_bradesco.yml"
    prefix:   /informacoes/configuracao/bradesco

folha_pagamento_bases_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_bases.yml"
    prefix:   /folha-pagamento/bases

pagamento_evento_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_evento.yml"
    prefix:   /folha-pagamento/evento

estagio_estagiario_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/estagio_estagiario.yml"
    prefix:   /estagio/estagiario

estagio_configuracao_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/estagio_configuracao.yml"
    prefix:   /estagio/configuracoes

estagio_instituicao_ensino_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/estagio_instituicao_ensino.yml"
    prefix:   /estagio/instituicao-ensino

estagio_entidade_intermediadora_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/estagio_entidade_intermediadora.yml"
    prefix:   /estagio/entidade-intermediadora

estagio_relatorios:
    resource: "@RecursosHumanosBundle/Resources/config/routing/estagio_relatorios.yml"
    prefix:   /estagio/relatorios

beneficio_relatorios:
    resource: "@RecursosHumanosBundle/Resources/config/routing/beneficio_relatorios.yml"
    prefix:   /beneficio/relatorios

beneficio_plano_saude_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/beneficio_plano_saude.yml"
    prefix:   /beneficio/plano-saude

beneficio_beneficiario_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/beneficio_beneficiario.yml"
    prefix:   /beneficio/beneficiario

api_search_agencias:
    path:     /api/search/agencias
    defaults: { _controller: "RecursosHumanosBundle:Api/Monetario:findAgenciasByBanco"}
    methods:  GET

api_search_contas_corrente:
    path:     /api/search/conta-corrente
    defaults: { _controller: "RecursosHumanosBundle:Api/Monetario:findContasCorrenteByAgencia"}
    methods:  GET

#TODO: Checar a necessidade dessa rota, ja que tem que ter s√≥ pra eventos
api_search_previdencia_eventos:
    path:     /api/search/prev-eventos
    defaults: { _controller: "RecursosHumanosBundle:Api/PrevidenciaEventos:getEventosByNatureza"}
    methods:  GET

informacoes_relatorios_index:
#    defaults: { _controller: "RecursosHumanosBundle:Informacoes/Relatorios:indexRelatorio" }
    resource: "@RecursosHumanosBundle/Resources/config/routing/informacoes_relatorios.yml"
    prefix:     /informacoes/relatorios

folha_pagamento_folhas_index:
    resource: "@RecursosHumanosBundle/Resources/config/routing/folha_pagamento_folhas.yml"
    prefix:    /folha-pagamento/folhas

rh_integracao:
    path:     /integracao
    defaults: { _controller: RecursosHumanosBundle:Integracao/Integracao:index }

recursos_humanos_contrato:
    resource: "@RecursosHumanosBundle/Resources/config/routing/Pessoal/Contrato/contrato.yml"
    prefix:   /contrato/contrato

recursos_humanos_ima:
    resource: "@RecursosHumanosBundle/Resources/config/routing/ima_exportar_remessa_bb.yml"
    prefix:   /ima

api_search_cargo_especialidade:
    path:     /api/search/cargo-especialidade
    defaults: { _controller: "RecursosHumanosBundle:Api/Especialidade:carregaCargoEspecialidade"}
    methods:  GET

api_search_especialidade_by_cargo:
    path:     /api/search/especialidade-by-cargo
    defaults: { _controller: "RecursosHumanosBundle:Api/Especialidade:carregaEspecialidadeByCargo"}
    methods:  GET

recursos_humanos_folha_pagamento_periodo_movimentacao_create:
    path:     /folha-pagamento/periodo-movimentacao/create
    defaults: { _controller: RecursosHumanosBundle:FolhaPagamento/PeriodoMovimentacao:new }
